language: python
python:
    - 2.7
    - 3.4
virtualenv:
    system_site_packages: true
before_install:
    - export DISPLAY=:99.0
    - pip install -U setuptools
    - wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    - conda create -q -n mic-test python=$TRAVIS_PYTHON_VERSION numpy scipy pillow scikit-learn scikit-image cytoolz pandas setuptools pip pymongo matplotlib six
    - source activate mic-test

    - pip install pytest pytest-cov
    - pip install coveralls

before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
    - python setup.py develop
    - py.test

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi

services:
    mongodb
