name: mic
dependencies:
- python=3.5*
- cytoolz
- h5py
- matplotlib=1.5*
- networkx
- numpy
- pandas
- pip
- pymongo=3*
- scikit-image
- scikit-learn
- scipy
- setuptools
- six
- toolz
- imageio
- pip:
  - coverage>=4.0
  - pytest>=2.8
  - pytest-cov>=2.2
  - sh>=1.11

